### ISSUE TITLE
Nimfuzzy Documentation Page is Down

### ISSUE THREAD

**Issue by tajmone** [genotrance/nimfuzz#1]
By following the documentation link provided in the README, I land on a 404 error page:

http://nimgen.genotrance.com/nimfuzzy

Thanks for wrapping this library! I had already come across it and it's really cool.

**Comment by genotrance** [comment]
Actually it is at http://nimgen.genotrance.com/nimfuzz/

I had to change the name due to a conflict.

I use it in my text editor but that's a nimterop based wrapper.

https://github.com/genotrance/feud/blob/master/wrappers/fuzzy.nim

**Comment by tajmone** [comment]
Thanks for the correct link, and for the text editor example of its usage (good to have).

**Comment by genotrance** [comment]
Fixed the link.
